<!--#Include File="Connection.asp"-->
<!--#MetaData Type="TypeLib"
	      File="H:\program files\Common Files\system\ado\msado15.dll"-->

<%
        strCapacity = 22
%>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="January%20-%20am_files/filelist.xml">
<style id="January - am_26149_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
-->
</style>
<link rel="stylesheet" type="text/css" href="Compass-Style.css" />
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="January - AM_26149" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=940 class=xl6326149
 style='border-collapse:collapse;table-layout:auto;width:940pt'>

 <col class=xl6326149 width=15 style='mso-width-source:userset;mso-width-alt:
 841;width:12pt'>

 <col class=xl6326149 width=15 span=10 style='mso-width-source:userset;
 mso-width-alt:950;width:15pt'>

 <col class=xl6326149 width=18 style='mso-width-source:userset;mso-width-alt:
 1133;width:15pt'>

 <col class=xl6326149 width=15 span=35 style='mso-width-source:userset;
 mso-width-alt:950;width:15pt'>

 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl6626149 colspan=10 width=200 style='height:12.75pt;
  width:240pt'>CORRECTIONAL DAILY ATTENDANCE ROSTER</td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
  <td class=xl6326149 width=26 style='width:20pt'></td>
<%
	dim rsPage
	dim strPage
	dim pageVar
		
	strPage = "SELECT COUNT(DISTINCT m.dc_number) FROM master_roster m INNER JOIN attend_hybrid_compass a ON m.dc_number = a.dc_number WHERE a.hybrid_group = '" & Session("Hybrid") & "' " & _
		  "AND class_date >= '"&Session("Month3")&"/1/"&Session("Year")&"' " & _
		  "AND class_date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"'"

	Set rsPage = Server.CreateObject("ADODB.Recordset")
	rsPage.Open strPage, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	pageVar = rsPage("")
%>

  <td class=xl6826149 colspan=4 width=104 style='width:80pt'>ROSTER PAGE</td>
  <td colspan=2 class=xl14426149 width=52 style='width:40pt'><Center>1</Center></td>
  <td class=xl7326149 width=26 style='width:20pt'>OF</td>
  <td colspan=2 class=xl14426149 width=52 style='width:40pt'><Center>

<%
	If pageVar <= 25 Then

		Response.Write "1"

	Else 

		Response.Write "2"

	End If

	rsPage.Close
	Set rsPage = Nothing
%>

</Center></td>
 </tr>
 <tr height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl6326149 style='height:12.75pt'></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
 </tr>
 <tr height=21 style='mso-height-source:userset;height:15.95pt'>
  <td height=21 class=xl7226149 colspan=5 style='height:15.95pt'>YEAR AND MONTH</td>
  <td class=xl7426149 colspan=3><%=Session("Month")%>, <%=Session("Year")%></td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  
  <td class=xl7226149 colspan=9><span style='mso-spacerun:yes'> 
  </span>INSTITUTION &amp; UNIT / FAC CODE #</td>
  <td class=xl11926149 colspan=9>Sumter C.I.&nbsp;<%=Session("Hybrid")%><span style='mso-spacerun:yes'> 
  </span>
  </td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  

<%
	dim rsTeacher
	dim strTeacher

	strTeacher = "SELECT teacher, class FROM teachers_tbl WHERE class LIKE '%" & Session("Dept") & "%'"

	Set rsTeacher = Server.CreateObject("ADODB.Recordset")	
	rsTeacher.Open strTeacher, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
%>
  
  <td class=xl7226149 colspan=3><span style='mso-spacerun:yes'> </span>TEACHER</td>
  <td class=xl7426149 colspan=8><%=rsTeacher("Teacher")%></td>
  
 </tr>
 <tr class=xl6326149 height=5 style='mso-height-source:userset;height:3.95pt'>
  <td height=5 class=xl6326149 style='height:3.95pt'></td>
  <td class=xl6726149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
  <td class=xl6553526149></td>
 </tr>
 <tr height=21 style='mso-height-source:userset;height:15.95pt'>
  <td height=21 class=xl7226149 colspan=4 style='height:15.95pt'>COURSE NAME</td>
  <td class=xl9026149></td>
  <td class=xl7426149 colspan=7><%=rsTeacher("Class")%>&nbsp;</td>
  <td>&nbsp;&nbsp;&nbsp;</td>
  <td>&nbsp;&nbsp;&nbsp;</td>


  <td class=xl7226149 colspan=4>COURSE CODE</td>
  <td class=xl7426149 colspan=14>
  
</td>
  <td class=xl7426149>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  
  <td class=xl7226149 colspan=3>SECTION</td>
  <td class=xl7426149 colspan=8> 

</td>
  
 </tr>

<TR>
	<TD>&nbsp;
</TR>
 <tr height=5 style='mso-height-source:userset;height:3.95pt'>
  <td height=5 class=xl6326149 style='height:3.95pt'></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6426149 style='border-top:none'>&nbsp;</td>
  <td class=xl6426149 style='border-top:none'>&nbsp;</td>
  <td class=xl6426149 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=21 style='mso-height-source:userset;height:10.95pt'>
  <td height=10 class=xl7226149 style='height:8.95pt' colspan=5>DAYS SCHEDULED</td>
  <td class=xl9926149 style='border-left:none'>Mon</td>
  <td class=xl8926149></td>
  <td class=xl9926149>Tue</td>
  <td class=xl8926149></td>
  <td class=xl9926149>Wed</td>
  <td class=xl8926149></td>
  <td class=xl9926149>Thu</td>
  <td class=xl8926149></td>
  <td class=xl9926149>Fri</td>
  <td class=xl8926149></td>
  <td class=xl9926149>Sat</td>
  <td class=xl8926149>&nbsp;</td>
  <td class=xl9926149>Sun</td>
  <td class=xl8926149>&nbsp;</td>
  <td class=xl6326149></td>
  
  <td class=xl12026149 colspan=5>CLASS SESSION<span style='mso-spacerun:yes'>  </span></td>
  <td colspan=2 class=xl15726149 style='border-right:.5pt solid black'>AM<span
  style='mso-spacerun:yes'>  </span></td>
  <td class=xl12126149 style='border-left:none'><Center>X</Center></td>
  <td colspan=2 class=xl16226149 style='border-right:.5pt solid black;
  border-left:none'>PM<span style='mso-spacerun:yes'>  </span></td>
  <td class=xl12126149 style='border-left:none'><Center>X</Center></td>
  <td colspan=2 class=xl15726149 style='border-right:.5pt solid black'>All
  Day<span style='mso-spacerun:yes'>  </span></td>
  <td class=xl12126149 style='border-left:none'>&nbsp;</td>
  <td colspan=2 class=xl15726149 style='border-right:.5pt solid black'>Night<span
  style='mso-spacerun:yes'>  </span></td>
  <td class=xl12126149 style='border-left:none'>&nbsp;</td>
  <td class=xl6326149></td>
  
  
  <td class=xl12026149 colspan=4>CLASS PERIOD<span style='mso-spacerun:yes'>  </span></td>
  <td class=xl6326149></td>
  <td class=xl7426149>&nbsp;</td>
  
  <td class=xl7326149>TO</td>
  <td class=xl7426149>&nbsp;</td>
  
 </tr>
  <TR>
    <TD>&nbsp;
  </TR>
 <tr height=5 style='mso-height-source:userset;height:3.95pt'>
  <td height=5 class=xl6326149 style='height:3.95pt'></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
  <td class=xl6326149></td>
 </tr>
 <tr class=xl6526149 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl6526149 style='height:12.75pt'></td>
  <td colspan=7 rowspan=2 class=xl14526149 style='border-right:.5pt solid black;
  border-bottom:1.5pt solid black'>NAME (LAST, FIRST)</td>
  <td colspan=3 rowspan=2 class=xl14526149 style='border-bottom:1.5pt solid black'>DC#</td>
  <td class=xl11226149></td>
  <%
        for calDayCount = 1 to 31
                css = "xl7026149"
            if calDayCount = 1 then
                css = "xl6926149"
            elseif calDayCount = 31 then
                css = "xl7126149"
            end if

            Response.Write "<td class="&css&" style='border-left:none'>" & calDayCount & "</td>"
         
        next
  %>
  <td colspan=2 rowspan=2 class=xl15126149 width=52 style='border-right:.5pt solid black;
  border-bottom:1.5pt solid black;width:40pt'>Ttl Days Attended</td>
  <td colspan=2 rowspan=2 class=xl15526149 width=52 style='border-right:.5pt solid black;
  border-bottom:1.5pt solid black;width:40pt'>Ttl Hrs Attended</td>
 </tr>
 <tr class=xl6526149 height=18 style='height:13.5pt'>
  <td height=18 class=xl6526149 style='height:13.5pt'></td>
  <td class=xl11326149></td>
  <%
        for calCount = 1 to 31
                css = "xl9526149"
            if calCount = 1 then
                css = "xl9426149"
            elseif calCount = 31 then
                css = "xl9626149"
            end if

            if calCount <= Session("Days3") then
                Select Case Weekday(Session("Month3") & "/"&calCount&"/" & Session("Year"))
		            Case 1
			            myDay = "Su"
		            Case 2
			            myDay = "M"
		            Case 3
			            myDay = "T"
		            Case 4
			            myDay = "W"
		            Case 5
			            myDay = "Th"
		            Case 6
			            myDay = "F"
		            Case 7
			            myDay = "Sa"
	            End Select
                Response.Write "<td class="&css&" align=center style='border-left:none'>"&myDay&"</td>"
            else
                Response.Write "<td class="&css&" style='border-left:none'>&nbsp;</td>"
            end if
        next
  %>
 </tr>

<%
	dim strDetail
	dim strStatus 
	dim rsDetail
	dim rsStatus
	dim rsCheckpm
    dim hunCount

    hunCount = 0

	strDetail = "SELECT DISTINCT m.dc_number, last_name, first_name, a.hybrid_group " & _
                "FROM master_roster m INNER JOIN attend_hybrid_compass a ON a.dc_number = m.dc_number " & _
                "inner join class_assignment c on a.dc_number = c.dc_number " & _
                "WHERE Class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'" & _
		        "AND Class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"'" & _
		        "AND a.hybrid_group = '" & Session("Hybrid") & "' ORDER BY last_name"

	
	Set rsDetail = Server.CreateObject("ADODB.Recordset")
	

	rsDetail.Open strDetail, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
	
%>

 <tr height=21 style='mso-height-source:userset;height:13.25pt'>
  <td height=21 class=xl9726149 style='height:10.95pt'>1</td>
  <td colspan=7 class=xl15926149 style='border-right:.5pt solid black;border-left:none'>

<% 	
    Set rsHourpull = Server.CreateObject("ADODB.Recordset")
    total_present = 0
	If Not rsDetail.EOF Then

	  Response.Write "" & rsDetail("Last_Name") & ", " & rsDetail("First_Name") & " "

'        if rsDetail("Grad") = "Grad" then
'            response.Write " <b>(Grad)</b>"
'        end if

	Else

	  Response.Write "&nbsp;"

	End If

	Response.Write 	"</td>" & _
  			"<td colspan=3 class=xl14226149 style='border-left:none'>"

	If Not rsDetail.EOF Then			
	
	Response.Write "" & rsDetail("dc_number") & ""

    strStatus = "SELECT hours, Class_Date FROM attend_hybrid_compass WHERE class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'" & _
		    "AND class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"' AND hybrid_group LIKE '%" & Session("Hybrid") & "%'" & _
		    "AND dc_number LIKE '%" & rsDetail("dc_number") & "%'" & _
		    "ORDER BY Class_Date"

	Set rsStatus = Server.CreateObject("ADODB.Recordset")	
	rsStatus.Open strStatus, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	Else

	Response.Write "&nbsp;"

	End If

Response.Write _
		"</td>" & _
  		"<td class=xl11426149>"

	If Not rsDetail.EOF Then

		Response.Write "&nbsp;"

	End If

	Response.Write "</td>"
	intAddHours = 0

For cellCounter = 1 to 30

  Response.Write "<td class=xl9226149 style='border-left:none'>"
	
  If Not rsDetail.EOF Then

	If Not rsStatus.EOF Then

	   intDate = rsStatus("Class_Date")
	   intDateCheck = day(intDate)

	    If intDateCheck = cellCounter Then
              
		Response.Write rsStatus("hours")

'		    If rsStatus("hours") = "P" OR rsStatus("hours") = "E" Then
		    If IsNull(rsStatus("hours")) = False Then
		    
		        intAddHours = intAddHours + rsStatus("hours")
'		        intAddHours = intAddHours + inAddHours
'                total_present = total_present + 1
		    Else

		        intAddHours = intAddHours + 0

		    End If

	    rsStatus.MoveNext

        Else

	        Response.Write "&nbsp;"

	    End If

    Else

    	Response.Write "&nbsp;"

	End If

 End If

  Response.Write "</td>"

Next

Response.Write "<td class=xl9326149 style='border-left:none'>"
	
 If Not rsDetail.EOF Then

	If Not rsStatus.EOF Then

	   intDate = rsStatus("Class_Date")
	   intDateCheck = day(intDate)
       
	    If intDateCheck = 31 Then
              
		Response.Write rsStatus("hours")
		

'		    If rsStatus("hours") = "P" OR rsStatus("hours") = "E" Then
		    If IsNull(rsStatus("hours")) = False then 		    
		        intAddHours = rsStatus("hours") + intAddHours
'                total_present = total_present + 1

		    Else

		        intAddHours = intAddHours + 0

		    End If

	    rsStatus.MoveNext

       	Else

	    Response.Write "&nbsp;"

	    End If

    	Else

    	Response.Write "&nbsp;"

	End If

    End If

%>
</td>

    <td colspan=2 class=xl12726149 style='border-right:.5pt solid black;
  border-left:none'>

<%
	If Not rsDetail.EOF Then

	strDays = "SELECT COUNT(hours) FROM attend_hybrid_compass WHERE Class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'" & _
		  "AND Class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"' AND hybrid_group LIKE '%" & Session("Hybrid") & "%'" & _
		  "AND dc_number LIKE '%" & rsDetail("dc_number") & "%'"

	Set rsDays = Server.CreateObject("ADODB.Recordset")
	rsDays.Open strDays, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	Response.Write "" & rsDays("") & ""

	End If
%>
</td>
  <td colspan=2 class=xl12926149 style='border-right:.5pt solid black'>
<%
	If Not rsDetail.EOF Then
'These three lines are the originals

'	rsHours = rsDays("")	
'	intHours = rsHours * 3
'	Response.Write intHours

'These two lines come from S-2 Compass
'	Response.Write intAddHours
'   hoursDelivered = intAddHours + hoursDelivered

'Esty's experiments
	Response.Write intAddHours
	hoursDelivered = intAddHours + hoursDelivered

        if intAddHours = 100 then
            hunCount =  hunCount + 1
        End if
        
	End If
%>

</td>
 </tr>

<%
For bigCounter = 2 to 24
 	
	Response.Write  "<tr height=21 style='mso-height-source:userset;height:13.25pt'>" & _
  			"<td height=21 class=xl7526149 style='height:10.95pt;border-top:none'>"&bigCounter&"</td>" & _
  			"<td colspan=7 class=xl14226149 style='border-right:.5pt solid black;border-left:none'>" 
		

	If Not rsDetail.EOF Then

	   rsDetail.MoveNext

	   If Not rsDetail.EOF Then

	  Response.Write "" & rsDetail("Last_Name") & ", " & rsDetail("First_Name") & ""

'        if rsDetail("Grad") = "Grad" then
'            response.Write " <b>(Grad)</b>"
'        end if

	Else

	  Response.Write "&nbsp;"

	End If

	End If


	Response.Write  "</td>" & _
  			"<td colspan=3 class=xl14226149 style='border-left:none'>"

	If Not rsDetail.EOF Then


	Response.Write "" & rsDetail("dc_number") & ""


	strStatus = "SELECT hours, Class_Date FROM attend_hybrid_compass WHERE Class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'" & _
		    "AND Class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"' AND hybrid_group LIKE '%" & Session("Hybrid") & "%'" & _
		    "AND dc_number LIKE '%" & rsDetail("dc_number") & "%'" & _
		    "ORDER BY Class_Date"

	Set rsStatus = Server.CreateObject("ADODB.Recordset")	
	rsStatus.Open strStatus, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	Else

	Response.Write "&nbsp;"

	End If

Response.Write _
		"</td>" & _
  		"<td class=xl11526149 style='border-top:none'>"

	If Not rsDetail.EOF Then

		Response.Write "&nbsp;"

	End If

Response.Write "</td>"
  
intAddHours = 0
For cellCounter = 1 to 30

  Response.Write "<td class=xl9226149 style='border-left:none'>"
	
     If Not rsDetail.EOF Then

	If Not rsStatus.EOF Then

	   intDate = rsStatus("Class_Date")
	   intDateCheck = day(intDate)

	    If intDateCheck = cellCounter Then
              
		Response.Write rsStatus("hours")


'		If rsStatus("hours") = "P" OR rsStatus("hours") = "E" Then
		If IsNull(rsStatus("hours")) = False then 		    
		        intAddHours = rsStatus("hours") + intAddHours
'		     intAddHours = intAddHours + 3
             total_present = total_present + 1

		Else

		  intAddHours = intAddHours + 0

		End If

	    rsStatus.MoveNext

       	    Else

	    Response.Write "&nbsp;"

	    End If

    	Else

    	Response.Write "&nbsp;"

	End If

    End If

  Response.Write "</td>"

Next

Response.Write "<td class=xl9326149 style='border-left:none'>"
	
     If Not rsDetail.EOF Then

	If Not rsStatus.EOF Then

	   intDate = rsStatus("Class_Date")
	   intDateCheck = day(intDate)

	    If intDateCheck = 31 Then
              
			If IsNull(rsStatus("hours")) = False Then
			Response.Write rsStatus("hours") 
		    intAddHours = rsStatus("hours") + intAddHours
			End If    

		Else

		    intAddHours = intAddHours + 0

		End If

	    rsStatus.MoveNext

	    End If

	End if	

    


'BELOW IS CODE FOR LAST TWO COLUMNS. TTL DAYS ATTENDED AND TTL HOURS ATTENDED.

    Response.Write "&nbsp;" & _
			"</td>" & _
    			"<td colspan=2 class=xl12726149 style='border-right:.5pt solid black;border-left:none'>" 

			If Not rsDetail.EOF Then

			strDays = "SELECT COUNT(hours) FROM attend_hybrid_compass WHERE Class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'" & _
		  "AND Class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"' AND hybrid_group LIKE '%" & Session("Hybrid") & "%'" & _
		  "AND dc_number LIKE '%" & rsDetail("dc_number") & "%'"

			    Set rsDays = Server.CreateObject("ADODB.Recordset")
	            rsDays.Open strDays, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	            Response.Write "" & rsDays("") & ""
			

  			Response.Write "</td>" & _
  		 			"<td colspan=2 class=xl12926149 style='border-right:.5pt solid black'>"

				Response.Write intAddHours
				hoursDelivered = intAddHours + hoursDelivered

                    if intAddHours = 100 then
                        hunCount =  hunCount + 1
                    End if
				
			Else

			Response.Write "</td>" & _
  		 			"<td colspan=2 class=xl12926149 style='border-right:.5pt solid black'>&nbsp;"

			End If

			Response.Write "</td></tr>"

Next

'END OF 2 - 24 LOOP FOR ROWS. BELOW BEGINS CODE FOR ROW 25

	Response.Write _
 		"<tr height=21 style='mso-height-source:userset;height:13.25pt'>" & _
  		"<td height=21 class=xl7526149 style='height:10.95pt;border-top:none'>25</td>" & _
		"<td colspan=7 class=xl14226149 style='border-right:.5pt solid black;border-left:none'>"
		

	If Not rsDetail.EOF Then

	   rsDetail.MoveNext

	   If Not rsDetail.EOF Then


	  Response.Write "" & rsDetail("Last_Name") & ", " & rsDetail("First_Name") & ""

        if rsDetail("Grad") = "Grad" then
            response.Write " <b>(Grad)</b>"
        end if

	Else

	  Response.Write "&nbsp;"

	End If

	End If

	Response.Write 	"</td>" & _
  			"<td colspan=3 class=xl14226149 style='border-left:none'>"

	If Not rsDetail.EOF Then
	
	Response.Write "" & rsDetail("dc_number") & ""

	strStatus = "SELECT Status, Class_Date FROM attend_hybrid_compass WHERE Class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'" & _
		    "AND Class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"' AND hybrid_group LIKE '%" & Session("Number") & "%'" & _
		    "AND dc_number LIKE '%" & rsDetail("dc_number") & "%'" & _
		    "AND dept_job = 'Student' ORDER BY Class_Date"

	Set rsStatus = Server.CreateObject("ADODB.Recordset")	
	rsStatus.Open strStatus, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	Else

	Response.Write "&nbsp;"

	End If


	Response.Write "</td>" & _
  			"<td class=xl11526149 style='border-top:none'>"

	If Not rsDetail.EOF Then

		Response.Write "&nbsp;"

	End If

	Response.Write "</td>"
	intAddHours = 0
For cellCounter = 1 to 30

   Response.Write "<td class=xl9226149 style='border-left:none'>"
	
     If Not rsDetail.EOF Then

	If Not rsStatus.EOF Then

	   intDate = rsStatus("Class_Date")
	   intDateCheck = day(intDate)

	    If intDateCheck = cellCounter Then

	  		If IsNull(rsStatus("hours")) = False then 		 
	  			Response.Write rsStatus("hours")    
		        intAddHours = rsStatus("hours") + intAddHours
			End If
		rsStatus.MoveNext

       	    Else

	    Response.Write "&nbsp;"
	    End If

	Else

	 Response.Write "&nbsp;"

	End If

    End If

Response.Write "</td>"

Next

Response.Write "<td class=xl9326149 style='border-left:none'>"
	
     If Not rsDetail.EOF Then

	If Not rsStatus.EOF Then

	   intDate = rsStatus("Class_Date")
	   intDateCheck = day(intDate)

	    If intDateCheck = 31 Then
              
		
				If IsNull(rsStatus("hours")) = False Then
				Response.Write rsStatus("hours") 
				intAddHours = rsStatus("hours") + intAddHours
				End If
		     
		Else

		    intAddHours = intAddHours + 0

		End If

	    rsStatus.MoveNext

	    End If

	End if	

    


'BELOW IS CODE FOR LAST TWO COLUMNS. TTL DAYS ATTENDED AND TTL HOURS ATTENDED FOR ROW 25.

    Response.Write "&nbsp;" & _
			"</td>" & _
    			"<td colspan=2 class=xl12726149 style='border-right:.5pt solid black;border-left:none'>" 

			If Not rsDetail.EOF Then

			strDays = "SELECT COUNT(hours) FROM attend_btu_compass WHERE Class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'" & _
		  "AND Class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"' AND Class_Number LIKE '%" & Session("Number") & "%'" & _
		  "AND dc_number LIKE '%" & rsDetail("dc_number") & "%'" & _

                  "OR Class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'  AND Class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"' AND Class_Number LIKE '%" & Session("Number") & "%'" & _
                  "AND dc_number LIKE '%" & rsDetail("dc_number") & "%'" & _

                  "OR Class_Date >= '"&Session("Month3")&"/1/"&Session("Year")&"'  AND Class_Date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"' AND Class_Number LIKE '%" & Session("Number") & "%'" & _
                  "AND dc_number LIKE '%" & rsDetail("dc_number") & "%'"
                  
			Set rsDays = Server.CreateObject("ADODB.Recordset")
			rsDays.Open strDays, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	  		If rsCheckpm("") >= 1 Then

				dayTotal = rsDays("")	
	
				Response.Write dayTotal 

	  		Else 

				Response.Write "" & rsDays("") & ""

	  		End If
			

  			Response.Write "</td>" & _
  		 			"<td colspan=2 class=xl12926149 style='border-right:.5pt solid black'>"

				Response.Write intAddHours
                hoursDelivered = intAddHours + hoursDelivered

                if intAddHours = 100 then
                        hunCount =  hunCount + 1
                End if

				rsCheckpm.Close

			Else

			Response.Write "</td>" & _
  		 			"<td colspan=2 class=xl12926149 style='border-right:.5pt solid black'>&nbsp;"

			End If

			Response.Write "</td></tr>"

%>

 <tr height=21 style='mso-height-source:userset;height:13.95pt'>
  <td colspan=12 height=21 class=xl13626149 style='border-right:1.5pt solid black;
  height:10.95pt'>TOTAL MEMBERSHIP EACH DAY</td>
<%
    for memCount = 1 to 28
    cssCol = "xl8426149"
    if memCount = 1 then
        cssCol = "xl8326149"
    elseif memCount = 31 then
        cssCol = ""
    end if

    response.write "<td class="&cssCol&" style='border-left:none'>"
	dim wDay, total_Membership_count, daily_Membership_count

	wDay = Weekday(""&Session("Month3")&"/"&memCount&"/"&Session("Year")&"")

	If wDay <> "1" AND wDay <> "7" Then

	dim rsMember
	dim strMember

	strMember = "SELECT COUNT(hours) FROM attend_hybrid_compass a inner join class_assignment c on a.dc_number = c.dc_number" & _
                " WHERE Class_Date = '"&Session("Month3")&"/"&memCount&"/"&Session("Year")&"'" & _
 		        "AND a.hybrid_group = '" & Session("Hybrid")&"'" 

	Set rsMember = Server.CreateObject("ADODB.Recordset")
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	Response.Write "" & rsMember("") & ""

        daily_Membership_count = rsMember("")

        total_Membership_count = daily_membership_count + total_Membership_count

	Else

	Response.Write "&nbsp"

	End If
    response.write "</td>"
    next
%>
  <td class=xl8426149 style='border-left:none'>
    <%
	If Session("Days3") > 28 Then

	wDay = Weekday(""&Session("Month3")&"/29/"&Session("Year")&"")

	If wDay <> "1" AND wDay <> "7" Then

	strMember = "SELECT COUNT(hours) FROM attend_hybrid_compass a inner join class_assignment c on a.dc_number = c.dc_number" & _
                " WHERE Class_Date = '"&Session("Month3")&"/29/"&Session("Year")&"'" & _
 		        "AND a.hybrid_group = '" & Session("Hybrid") & "'"   

	Set rsMember = Server.CreateObject("ADODB.Recordset")
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	Response.Write "" & rsMember("") & ""


	daily_Membership_count = rsMember("")

        total_Membership_count = total_Membership_count  + daily_Membership_count


	Else

	Response.Write "&nbsp;"

	End If

        Else

	Response.Write "&nbsp;"

	End If
%>
  </td>
  <td class=xl8426149 style='border-left:none'>
  <%
	If Session("Days3") > 28 Then

	wDay = Weekday(""&Session("Month3")&"/30/"&Session("Year")&"")

	If wDay <> "1" AND wDay <> "7" Then

	strMember = "SELECT COUNT(hours) FROM attend_hybrid_compass a inner join class_assignment c on a.dc_number = c.dc_number" & _
                " WHERE Class_Date = '"&Session("Month3")&"/30/"&Session("Year")&"'" & _
 		        " AND a.hybrid_group = '" & Session("hybrid") & "'"  

	Set rsMember = Server.CreateObject("ADODB.Recordset")
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	Response.Write "" & rsMember("") & ""


	daily_Membership_count = rsMember("")

        total_Membership_count = total_Membership_count  + daily_Membership_count

	Else

	Response.Write "&nbsp;"

	End If

        Else

	Response.Write "&nbsp;"

	End If
%>
  </td>
  <td class=xl8426149 style='border-left:none'>
<%
	If Session("Days3") > 30 Then

	wDay = Weekday(""&Session("Month3")&"/31/"&Session("Year")&"")

	If wDay <> "1" AND wDay <> "7" Then

	strMember = "SELECT COUNT(hours) FROM attend_hybrid_compass a inner join class_assignment c on a.dc_number = c.dc_number" & _
                " WHERE Class_Date = '"&Session("Month3")&"/31/"&Session("Year")&"'" & _
 		        "AND a.hybrid_group = '" & Session("hybrid") & "'"  

	Set rsMember = Server.CreateObject("ADODB.Recordset")
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText

	Response.Write "" & rsMember("") & ""


	daily_Membership_count = rsMember("")

        total_Membership_count = total_Membership_count  + daily_Membership_count


	Else

	Response.Write "&nbsp;"

	End If

        Else

	Response.Write "&nbsp;"

	End If
%>

</td>
  
  <td colspan=4 class="blnk" width=104 style='border-left:1.5pt solid black;  height:10.95pt' style='border-right:.5pt solid black; width:80pt'>




</td>
 </tr>
 <tr height=21 style='mso-height-source:userset;height:13.95pt'>
  <td colspan=12 height=21 class=xl13926149 style='border-right:1.5pt solid black;
  height:10.95pt'>Total Compass 100 Students Served Each Day</td>
  <td class=xl8626149 style='border-top:none;border-left:none'>
<%
	wDay = Weekday(""&Session("Month3")&"/1/"&Session("Year")&"")

	If wDay <> "1" AND wDay <> "7" Then

		strMember = "SELECT hours FROM attend_hybrid_compass WHERE Class_Date = '"&Session("Month3")&"/1/"&Session("Year")&"' " & _
					"AND hybrid_group = '" & Session("Number")&"'"
		
	    Set rsMember = Server.CreateObject("ADODB.Recordset")
		rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
		intHours = 0
			do while not rsMember.eof

				    intHours = rsMember("hours") + intHours

				rsMember.MoveNext
			loop

		Response.Write intHours
		rsMember.Close
		Else
		Set rsMember = Server.CreateObject("ADODB.Recordset")
		Response.Write "&nbsp;"

		End If
					

%>
</td>
<%
    for tpCount = 2 to 28
	response.write "<td class=xl8726149 style='border-top:none;border-left:none'>"
	wDay = Weekday(""&Session("Month3")&"/"&tpCount&"/"&Session("Year")&"")

	If wDay <> "1" AND wDay <> "7" Then

	strMember = "SELECT hours FROM attend_hybrid_compass WHERE class_date = '"&Session("Month3")&"/"&tpCount&"/"&Session("Year")&"'" & _
 		        "AND hybrid_group = '" & Session("Hybrid") & "' "
 		        
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
    intHours = 0
		do while not rsMember.eof

				intHours = rsMember("hours") + intHours

			rsMember.MoveNext
		loop

		Response.Write intHours
		rsMember.Close
		Else

		Response.Write "&nbsp;"

		End If
		response.write "</td>"
		next
    
    
 %>
<td class=xl8726149 style='border-top:none;border-left:none'>
 <%
	If Session("Days3") > 28 Then

	wDay = Weekday(""&Session("Month3")&"/29/"&Session("Year")&"")

	If wDay <> "1" AND wDay <> "7" Then

	strMember = "SELECT hours FROM attend_hybrid_compass WHERE Class_Date = '"&Session("Month3")&"/29/"&Session("Year")&"'" & _
				"AND hybrid_group = '" & Session("Hybrid")& "'"

	Set rsMember = Server.CreateObject("ADODB.Recordset")
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
	inthours = 0
		do while not rsMember.eof

				    intHours = rsMember("hours") + intHours

				rsMember.MoveNext
			loop

		Response.Write intHours
		rsMember.Close
		Else
		Set rsMember = Server.CreateObject("ADODB.Recordset")
		Response.Write "&nbsp;"

		End If
				
%>

</td>

  <td class=xl8726149 style='border-top:none;border-left:none'>
<%
	If Session("Days3") > 28 Then

	wDay = Weekday(""&Session("Month3")&"/30/"&Session("Year")&"")

	If wDay <> "1" AND wDay <> "7" Then

	strMember = "SELECT hours FROM attend_hybrid_compass WHERE Class_Date = '"&Session("Month3")&"/30/"&Session("Year")&"'" &_
				"AND hybrid_group = '" & Session("Hybrid")&"'"

	Set rsMember = Server.CreateObject("ADODB.Recordset")
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
	inthours = 0
	
	do while not rsMember.eof

				    intHours = rsMember("hours") + intHours

				rsMember.MoveNext
			loop

		Response.Write intHours
		rsMember.Close
		Else
		Set rsMember = Server.CreateObject("ADODB.Recordset")
		Response.Write "&nbsp;"

		End If
		End if	
%>
</td>
  <td class=xl8726149 style='border-top:none;border-left:none'>
<%
	If Session("Days3") > 30 Then

	wDay = Weekday(""&Session("Month3")&"/31/"&Session("Year")&"")
	
	strMember = "SELECT hours FROM attend_hybrid_compass WHERE Class_Date = '"&Session("Month3")&"/31/"&Session("Year")&"'" &_
				"AND hybrid_group = '" & Session("Hybrid")&"'"

	Set rsMember = Server.CreateObject("ADODB.Recordset")
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
	inthours = 0
	
	do while not rsMember.eof

				    intHours = rsMember("hours") + intHours

				rsMember.MoveNext
			loop

		Response.Write intHours 
		rsMember.Close
		Else
		Set rsMember = Server.CreateObject("ADODB.Recordset")
		Response.Write "&nbsp;"

		End If
		End if	
		
%>

</td>
  
  <td colspan=4 class="blnk2" width=104 style='border-left:1.5pt solid black;  height:10.95pt' style='border-right:.5pt solid black; width:80pt'>




</td>
 </tr>

 
 <tr class=xl6553526149 height=24 style='mso-height-source:userset;height:14.0pt'>
  <td height=24 class=xl6726149 style='height:14.0pt'></td>
  <td class=xl6553526149></td>
  
  <td class=xl6726149 colspan=6>TOTAL CLASS DAYS / MONTH:</td>
  
  <td colspan=2 class=xl12226149>
<%


 	DIM total_class_days

        strMember = "SELECT COUNT(DISTINCT class_date) FROM attend_hybrid_compass WHERE class_date >= '"&Session("Month3")&"/1/"&Session("Year")&"'" & _
 		            "AND class_date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"'" & _
		            "AND hybrid_group = '" & Session("Hybrid") & "'"
                    
	Set rsMember = Server.CreateObject("ADODB.Recordset")
	rsMember.Open strMember, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
        

       total_class_days = rsMember("")

       Response.Write "<Center>" & rsMember("") & "</Center>"


%>
</td>
  <TD>&nbsp;</td>
  <TD>&nbsp;</td>
  <td class=xl6726149 colspan=9>TOTAL STUDENT ATTEND. DAYS / MONTH:</td>

  <td colspan=2 class=xl12326149>


<%
        <!--This line of code is to fill-in the Total Student Attend Days/Month  Bottom-Middle of form; -->
        <!--Using information stored in the variable Total_Present declared and filled from the total -->
        <!--present each day SQL run; -->


	
	Response.Write "<Center>" & Total_present & "</Center>"
        
%>

</td>

  <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>

  <td class=xl6726149 colspan=12>
   TOTAL COMPASS 100 HOURS DELIVERED THIS MONTH:
  </td>

  <td class=xl11726149 style='border-top:none'>&nbsp;</td>
  <td Colspan=2 class=xl10026149 style='border-top:none'>
<%
	
        <!--This line of code is to fill-in Average Daily Attendance  Bottom-right of form; -->
        <!--Using information stored in the variable Total_Present declared and filled from the total -->
        <!--present each day SQL run; and total_class_days variable declared and filled from SQL toal class per month-->

         dim intAverage
	    dim intConvert
        dim strHoursQuery
        
        strHoursQuery = "select hours from attend_hybrid_compass where class_date >= '"&Session("Month3")&"/1/"&Session("Year")&"' and class_date <= '"&Session("Month3")&"/"&Session("Days3")&"/"&Session("Year")&"'" & _
                         "AND hybrid_group = '" & Session("Hybrid") & "'"

        set rsHoursdb = Server.CreateObject("ADODB.Recordset")
        rsHoursdb.Open strHoursQuery, eduConn, adOpenForwardOnly, adLockReadOnly, adCmdText
        intAllserved = 0
        do while not rsHoursdb.eof
            intAllServed = intAllServed + rsHoursdb("hours")
        rsHoursdb.movenext
        loop
        rsHoursdb.close
        set rsHoursdb = nothing
        If total_present <> 0 Then 

          If total_class_days <> 0 Then

	intAverage = total_present / total_class_days

	intConvert = Left(intAverage, 5)
	       

	Response.Write "<Center>" & intAllServed & "</Center>"

	End If
	
	Else    

	Response.Write "<Center>0</Center>"	
	
	End If
	
%>		
</td>
</tr>

<tr class=xl6553526149 height=24 style='mso-height-source:userset;height:14.0pt'>
  <td colspan=23 height=24 class=xl6726149 style='border:1pt solid black; height:14.0pt'>Calculate Program Hours: Modules 1 - 5 = 15 hours per module; Module 6 = 24 hours; Portfolio= 1 hour<BR>
  ENR - enrolled; P = present, no hours earned; number = hours earned; CMP = complete</td>
  <td class=xl6553526149 colspan=8></td>
    
  <td class=xl6726149 colspan=12>TOTAL COMPASS 100 COMPLETE THIS MONTH:</td>
  <td class=xl11726149 style='border-top:none'>&nbsp;</td>
  <td colspan=2 class=xl10026149 style='border-top:none'>
<%
    
    Response.Write "<Center>" & hunCount & "</Center>"
    
%>
  </td>
</tr>

 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=23 style='width:17pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=31 style='width:23pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
  <td width=26 style='width:20pt'></td>
 </tr>
 <![endif]>
</table>

</div>
<BR>

</body>
</html>




